# Generated by Django 5.2.6 on 2025-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_image/<function user_directory_path at 0x000001F3AA7D7420>/%Y/%m/%d/'),
        ),
    ]
