# Generated by Django 5.2.6 on 2025-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_image/<django.db.models.fields.CharField>/%Y/%m/%d/'),
        ),
    ]
