# Generated by Django 5.2.6 on 2025-10-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, default='404.jpg', null=True, upload_to='profile_image/%Y/%m/%d/'),
        ),
    ]
