# Generated by Django 5.2.6 on 2025-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
