# Generated by Django 5.2.6 on 2025-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
