# Generated by Django 5.2.6 on 2025-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_merge_20251013_2256'),
        ('users', '0014_user_favorite_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(related_name='matched_with', through='matching.Match', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='swipes',
            field=models.ManyToManyField(related_name='swiped_by', through='matching.Swipe', to='users.user'),
        ),
    ]
