# Generated by Django 5.2.6 on 2025-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_notified',
            field=models.BooleanField(default=False),
        ),
    ]
