# Generated by Django 5.2.6 on 2025-10-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualplaylist',
            name='spotify_playlist_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mutualplaylist',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
