# Generated by Django 5.2.6 on 2025-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualplaylist',
            name='playlist_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
