# Generated by Django 5.2.6 on 2025-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_mutualplaylist_playlist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualplaylist',
            name='playlist_url',
        ),
        migrations.AddField(
            model_name='match',
            name='playlist_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
