# Generated by Django 5.2.6 on 2025-10-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_remove_mutualplaylist_playlist_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='playlist_url',
        ),
        migrations.AddField(
            model_name='mutualplaylist',
            name='playlist_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
