# Generated by Django 5.2.6 on 2025-10-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_mutualplaylist_spotify_playlist_id_and_more'),
        ('matching', '0004_remove_match_playlist_url_and_more'),
    ]

    operations = [
    ]
