# Generated by Django 5.2.6 on 2025-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_merge_20251013_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualplaylist',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
